import "./globals.css";
import "@repo/ui/styles.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import RecoilProvider from "./components/RecoilProvider";
import NextAuthSessionWrapper from "./components/NextAuthSessionWrapper";
import AppBar from "./components/AppBar";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): JSX.Element {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NextAuthSessionWrapper>
      <AppBar/> 
          <RecoilProvider>{children}</RecoilProvider>
        </NextAuthSessionWrapper>
      </body>
    </html>
  );
}
